### ISSUE TITLE
NullPointerException MSA.java:424

### ISSUE THREAD

**Issue by Troughy** [PlanetTeamSpeakk/DevLogin#4] opened 2022-11-01 15:08 UTC
I've been using devlogin for a couple of days now and never had any issues with it, until today
I'm running my fabric mod from IntelliJ with --msa added to the program arguments, and I'm getting this error:
```
[pool-2-thread-1/ERROR] (FabricLoader) Uncaught exception in thread "pool-2-thread-1"
 java.lang.NullPointerException: null
	at java.io.Reader.<init>(Reader.java:168) ~[?:?]
	at java.io.InputStreamReader.<init>(InputStreamReader.java:76) ~[?:?]
	at fabric.com.ptsmods.devlogin.MSA.lambda$doRequest$15(MSA.java:424) ~[devlogin-3.1.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```
I tried restarting intellij, tried --msa-nostore, nothing changed.

**Comment by TechnologicNick** [comment] 2022-11-01 16:45
I also just got this. Deleting the `run/DevLoginCache.json` file fixes it.

**Comment by PlanetTeamSpeakk** [comment] 2022-11-01 18:25
Guessing Microsoft maybe now lets refresh tokens expire? Not sure, but something on Microsoft's side is not approving of how we do things anymore.

**Comment by Qendolin** [comment] 2022-11-11 10:23
This error occurs once every day for me, re-authenticating every time is getting quite annoying. Any ideas what might cause that?

**Comment by PlanetTeamSpeakk** [comment] 2022-11-11 10:35
> This error occurs once every day for me, re-authenticating every time is getting quite annoying. Any ideas what might cause that?

I assume Microsoft now lets refresh tokens expire after a day which they never did before. I'm not sure if there's anything I can do to circumvent this, but I'll have a look.

**Comment by TechnologicNick** [comment] 2022-11-12 17:58
I am using `--msa-nostore` however, the refresh token shouldn't be stored.

**Comment by PlanetTeamSpeakk** [comment] 2022-11-12 20:54
> I am using `--msa-nostore` however, the refresh token shouldn't be stored.

In that case, you'll have to re-authenticate every time your session expires anyway.
I think that the error may be caused by the game token now being invalid in a different stage than it was before or the servers now respond differently to an expired token which would mean there's nothing wrong with the refresh token, it just doesn't get used.
But since the requests are done async, the stack trace isn't very helpful.

**Comment by confiteria** [comment] 2022-11-18 20:01
Understand this isn't your fault but Microsoft really be trying to make this worse and worse. Past couple weeks I had to delete the json and relog about once a day, now since yesterday it's been nearly hourly.

**Comment by PlanetTeamSpeakk** [comment] 2022-11-18 21:14
That does sure sound inconvient, I'll have a look at this tomorrow, see if I can find a solution.

**Comment by PlanetTeamSpeakk** [comment] 2023-04-22 17:10
Sorry for the big delay, I still haven't got a clue what caused this issue all of a sudden, but with the latest version, this is now fixed.

**Closed as completed by PlanetTeamSpeakk** 2023-04-22 17:10 UTC

**Comment by RedLime** [comment] 2023-05-01 09:03
Oh it was very annoying problem, thanks for fix this :D
